In [8]:
import torch
import random
import numpy as np
from collections import deque

In [35]:
memory = deque(maxlen=10000)

for i in range(10):
    state = torch.rand([3,300,300])
    next_state = torch.rand([3,300,300])
    action = torch.randint(10,[1])
    reward = torch.randint(10,[1])
    done = torch.tensor([True])
    memory.append((state, next_state, action, reward, done))


In [36]:
batch = random.sample(memory, 5)

In [54]:
for i in zip(*batch):
    print(i[0])
    break

tensor([[[0.8565, 0.6944, 0.4694,  ..., 0.6397, 0.0426, 0.3548],
         [0.1489, 0.1753, 0.7417,  ..., 0.6325, 0.9271, 0.8369],
         [0.7824, 0.5868, 0.3576,  ..., 0.8722, 0.1322, 0.5785],
         ...,
         [0.9688, 0.9520, 0.9081,  ..., 0.3218, 0.9856, 0.0538],
         [0.6089, 0.4578, 0.5012,  ..., 0.1186, 0.9008, 0.5609],
         [0.7446, 0.8416, 0.6212,  ..., 0.0705, 0.2568, 0.0375]],

        [[0.1735, 0.1816, 0.9032,  ..., 0.6709, 0.3611, 0.0885],
         [0.4150, 0.9308, 0.3125,  ..., 0.9040, 0.0766, 0.4616],
         [0.5715, 0.4028, 0.3390,  ..., 0.5164, 0.8946, 0.1464],
         ...,
         [0.4599, 0.9054, 0.8319,  ..., 0.2897, 0.6258, 0.0344],
         [0.2253, 0.1596, 0.8117,  ..., 0.0568, 0.4598, 0.2567],
         [0.8172, 0.0498, 0.8210,  ..., 0.5857, 0.0255, 0.9988]],

        [[0.8833, 0.9012, 0.0879,  ..., 0.5765, 0.5999, 0.3854],
         [0.4328, 0.9845, 0.2761,  ..., 0.6730, 0.1366, 0.6975],
         [0.1451, 0.3931, 0.7160,  ..., 0.8903, 0.7060, 0.

In [56]:
print(tuple(zip(*batch))[0])

(tensor([[[0.8565, 0.6944, 0.4694,  ..., 0.6397, 0.0426, 0.3548],
         [0.1489, 0.1753, 0.7417,  ..., 0.6325, 0.9271, 0.8369],
         [0.7824, 0.5868, 0.3576,  ..., 0.8722, 0.1322, 0.5785],
         ...,
         [0.9688, 0.9520, 0.9081,  ..., 0.3218, 0.9856, 0.0538],
         [0.6089, 0.4578, 0.5012,  ..., 0.1186, 0.9008, 0.5609],
         [0.7446, 0.8416, 0.6212,  ..., 0.0705, 0.2568, 0.0375]],

        [[0.1735, 0.1816, 0.9032,  ..., 0.6709, 0.3611, 0.0885],
         [0.4150, 0.9308, 0.3125,  ..., 0.9040, 0.0766, 0.4616],
         [0.5715, 0.4028, 0.3390,  ..., 0.5164, 0.8946, 0.1464],
         ...,
         [0.4599, 0.9054, 0.8319,  ..., 0.2897, 0.6258, 0.0344],
         [0.2253, 0.1596, 0.8117,  ..., 0.0568, 0.4598, 0.2567],
         [0.8172, 0.0498, 0.8210,  ..., 0.5857, 0.0255, 0.9988]],

        [[0.8833, 0.9012, 0.0879,  ..., 0.5765, 0.5999, 0.3854],
         [0.4328, 0.9845, 0.2761,  ..., 0.6730, 0.1366, 0.6975],
         [0.1451, 0.3931, 0.7160,  ..., 0.8903, 0.7060, 0

In [61]:
torch.stack(tuple(zip(*batch))[-1]).shape

torch.Size([5, 1])

In [4]:
('abc'+'/'+'dcd')

'abc/dcd'

In [8]:
print(f"{'Episode':>8}{'Step':>8}{'Epsilon':>10}{'MeanReward':>15}"
f"{'MeanLength':>15}{'MeanLoss':>15}{'MeanQValue':>15}"
f"{'TimeDelta':>15}{'Time':>20}\n")

 Episode    Step   Epsilon     MeanReward     MeanLength       MeanLoss     MeanQValue      TimeDelta                Time



In [1]:
from pathlib import Path

In [5]:
save_dir = Path("checkpoints")
save_dir.mkdir(parents=True)

In [15]:
indices = torch.tensor([3, 3, 3], device='cuda:0')
indices * 0.9

tensor([2.7000, 2.7000, 2.7000], device='cuda:0')